# Generated by Django 5.2.8 on 2025-12-09 12:16
#
# verified: no released version of stapel-auth predates this migration —
# 0001_initial and 0002_initial were generated in the same makemigrations run
# (autodetector split of the AUTH_USER_MODEL FK) and shipped together in the
# repo's first commit/release (v0.2.0+); refreshtokentracker is created by
# 0001 moments before this AddField runs, so the table is always empty here.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(  # noqa: MIG004
            model_name='refreshtokentracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
