# Generated by Django 5.2.8 on 2026-02-10 09:38

import re
from django.db import migrations, models


def normalize_phones(apps, schema_editor):
    """Normalize existing phone numbers: strip spaces, dashes, parens."""
    PhoneVerification = apps.get_model('authentication', 'PhoneVerification')
    for pv in PhoneVerification.objects.all():
        phone = pv.phone.strip()
        if phone.startswith('+'):
            normalized = '+' + re.sub(r'[^\d]', '', phone[1:])
        else:
            normalized = re.sub(r'[^\d]', '', phone)
        if normalized != pv.phone:
            PhoneVerification.objects.filter(pk=pv.pk).update(phone=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='code',
            field=models.CharField(max_length=4),
        ),
        # Normalize phone data before shrinking column
        migrations.RunPython(normalize_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(db_index=True, max_length=18),
        ),
    ]
