# Generated by Django 5.2.8 on 2026-02-10 09:38
#
# stapel: contract-phase
# verified: no released version of stapel-auth predates this migration (it
# shipped in the repo's first commit/release, v0.2.0+, extracted from the
# monolith). otp/services.py already generates 4-digit codes and the current
# models.py matches these narrowed widths, so no released version of this
# package ever wrote wider values. Phone data is normalized via RunPython
# below before the phone column narrows; verification codes are ephemeral
# (~10 min TTL, otp/services.py) so no stale wide values persist.

import re
from django.db import migrations, models


def normalize_phones(apps, schema_editor):
    """Normalize existing phone numbers: strip spaces, dashes, parens."""
    PhoneVerification = apps.get_model('authentication', 'PhoneVerification')
    for pv in PhoneVerification.objects.all():
        phone = pv.phone.strip()
        if phone.startswith('+'):
            normalized = '+' + re.sub(r'[^\d]', '', phone[1:])
        else:
            normalized = re.sub(r'[^\d]', '', phone)
        if normalized != pv.phone:
            PhoneVerification.objects.filter(pk=pv.pk).update(phone=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='code',
            field=models.CharField(max_length=4),
        ),
        # Normalize phone data before shrinking column
        migrations.RunPython(normalize_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(db_index=True, max_length=18),
        ),
    ]
