# Generated by Django 5.2.8 on 2026-02-11 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_emailverification_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatorChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=10)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('change_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notification_day_1_sent', models.BooleanField(default=False)),
                ('notification_day_7_sent', models.BooleanField(default=False)),
                ('notification_day_13_sent', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authenticator_change_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='authenticat_user_id_0abf7f_idx'), models.Index(fields=['new_value', 'status'], name='authenticat_new_val_1b9ec6_idx'), models.Index(fields=['scheduled_at', 'status'], name='authenticat_schedul_4ac4ef_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'change_type'), name='unique_pending_change_per_user_type'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('new_value', 'change_type'), name='unique_pending_reservation')],
            },
        ),
    ]
