# Generated by Django 6.0.2 on 2026-06-18 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_sessions_totp_device'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_user_id_4d7d26_idx',
            old_name='usersession_user_revoked_idx',
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
