# Generated by Django 6.0.2 on 2026-06-18 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_usersession_user_revoked_idx_user_sessio_user_id_4d7d26_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('totp_enabled', 'Totp Enabled'), ('totp_disabled', 'Totp Disabled'), ('totp_login', 'Totp Login'), ('totp_step_up', 'Totp Step Up'), ('session_revoked', 'Session Revoked'), ('session_revoke_all', 'Session Revoke All'), ('account_locked', 'Account Locked'), ('account_unlock', 'Account Unlock'), ('suspicious_login', 'Suspicious Login'), ('magic_link_sent', 'Magic Link Sent'), ('magic_link_used', 'Magic Link Used'), ('passkey_registered', 'Passkey Registered'), ('passkey_login', 'Passkey Login'), ('passkey_removed', 'Passkey Removed'), ('oauth_login', 'Oauth Login')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='authentication.usersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='auth_audit__user_id_cc0a4a_idx'), models.Index(fields=['event_type', 'created_at'], name='auth_audit__event_t_c6f4b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credential_id', models.BinaryField(max_length=1024, unique=True)),
                ('public_key', models.BinaryField(max_length=4096)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, max_length=36)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('transports', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passkey_credentials',
                'indexes': [models.Index(fields=['user', 'is_active'], name='passkey_cre_user_id_597035_idx')],
            },
        ),
    ]
