# Generated by Django 6.0.2 on 2026-06-18 21:53
#
# verified: no released version of stapel-auth predates this migration —
# 0001-0010 all shipped together in the repo's first commit/release (v0.2.0+,
# extracted from the monolith on 2026-06-24); there is no N-1 released
# version of THIS package whose code omits device_details from its INSERTs,
# so the migrate->swap compatibility window MIG004 warns about does not
# exist for any customer of this package.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_audit_log_passkeys_suspicious_session'),
    ]

    operations = [
        migrations.AddField(  # noqa: MIG004
            model_name='usersession',
            name='device_details',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('api', 'API'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
