# Generated by Django 6.0.2 on 2026-06-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_audit_log_passkeys_suspicious_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_details',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('api', 'API'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
