# Generated by Django 6.0.6 on 2026-07-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_verification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('totp_enabled', 'Totp Enabled'), ('totp_disabled', 'Totp Disabled'), ('totp_login', 'Totp Login'), ('totp_step_up', 'Totp Step Up'), ('session_revoked', 'Session Revoked'), ('session_revoke_all', 'Session Revoke All'), ('account_locked', 'Account Locked'), ('account_unlock', 'Account Unlock'), ('suspicious_login', 'Suspicious Login'), ('magic_link_sent', 'Magic Link Sent'), ('magic_link_used', 'Magic Link Used'), ('passkey_registered', 'Passkey Registered'), ('passkey_login', 'Passkey Login'), ('passkey_removed', 'Passkey Removed'), ('oauth_login', 'Oauth Login'), ('qr_login', 'Qr Login'), ('sso_login', 'Sso Login'), ('totp_failed', 'Totp Failed'), ('captcha_failed', 'Captcha Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orgmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ssoconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
