# Generated by Django 6.0.7 on 2026-07-16 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_widen_sso_config_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedOAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='OAuth provider id, e.g. google, github.', max_length=50)),
                ('provider_user_id', models.CharField(help_text="The provider's own user id — keyed on this (not email) for account-takeover-safe uniqueness.", max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email reported by the provider, if any (display only).', max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, help_text='Provider display name/username, if any (display only).', max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='When this account was linked.')),
                ('user', models.ForeignKey(help_text='The account this link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='linked_oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'linked_oauth_accounts',
                'ordering': ['-linked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_provider_per_user'), models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_provider_account')],
            },
        ),
    ]
