# Generated by Django 6.0.7 on 2026-07-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_linkedoauthaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('totp_enabled', 'Totp Enabled'), ('totp_disabled', 'Totp Disabled'), ('totp_login', 'Totp Login'), ('session_revoked', 'Session Revoked'), ('session_revoke_all', 'Session Revoke All'), ('account_locked', 'Account Locked'), ('account_unlock', 'Account Unlock'), ('suspicious_login', 'Suspicious Login'), ('magic_link_sent', 'Magic Link Sent'), ('magic_link_used', 'Magic Link Used'), ('passkey_registered', 'Passkey Registered'), ('passkey_login', 'Passkey Login'), ('passkey_removed', 'Passkey Removed'), ('oauth_login', 'Oauth Login'), ('qr_login', 'Qr Login'), ('sso_login', 'Sso Login'), ('totp_failed', 'Totp Failed'), ('captcha_failed', 'Captcha Failed')], max_length=50),
        ),
    ]
