# Generated by Django 6.0.7 on 2026-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_authauditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatorchangerequest',
            name='change_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('totp', 'TOTP')], max_length=10),
        ),
    ]
