# Generated by Django 6.0.7 on 2026-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_authenticatorchangerequest_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
