# Generated by Django 6.0.7 on 2026-09-01 23:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_authauditlog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('merged_id', models.UUIDField(db_index=True, help_text='The guest account that was absorbed and then deleted.', unique=True)),
                ('survivor_id', models.UUIDField(db_index=True, help_text="The account that survived and now owns the guest's rows.")),
                ('merged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('email_otp', 'Email OTP'), ('phone_otp', 'Phone OTP'), ('oauth_identity', 'OAuth provider identity'), ('oauth_email', 'OAuth verified email'), ('unknown', 'Unknown')], default='unknown', help_text='Which proof identified the survivor.', max_length=32)),
            ],
            options={
                'db_table': 'auth_user_merge',
                'ordering': ['-merged_at'],
                'indexes': [models.Index(fields=['survivor_id', 'merged_at'], name='auth_user_m_survivo_d17b67_idx')],
            },
        ),
    ]
