# Generated by Django 6.0.8 on 2026-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_usermerge'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='previous_jti',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
