# Generated by Django 6.0.8 on 2026-09-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_session_refresh_rotation_grace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.CharField(max_length=512)),
                ('click_id_type', models.CharField(choices=[('gclid', 'gclid'), ('gbraid', 'gbraid'), ('wbraid', 'wbraid')], max_length=16)),
                ('captured_at', models.DateTimeField()),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signup Attribution',
                'verbose_name_plural': 'Signup Attributions',
                'db_table': 'auth_signup_attribution',
                'indexes': [models.Index(fields=['click_id'], name='signup_attr_click_idx')],
            },
        ),
    ]
